language: rust
rust: nightly
sudo: false

cache:
  cargo: true
  directories:
  - clippy_lints/target

env:
 global:
   # TRAVIS_TOKEN_CLIPPY_SERVICE
   secure: dj8SwwuRGuzbo2wZq5z7qXIf7P3p7cbSGs1I3pvXQmB6a58gkLiRn/qBcIIegdt/nzXs+Z0Nug+DdesYVeUPxk1hIa/eeU8p6mpyTtZ+30H4QVgVzd0VCthB5F/NUiPVxTgpGpEgCM9/p72xMwTn7AAJfsGqk7AJ4FS5ZZKhqFI=

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install remark-cli remark-lint

script:
 - remark -f README.md > /dev/null
 - python util/update_lints.py -c
 - set -e
 - cargo build --features debugging
 - cargo test --features debugging
 - mkdir -p ~/rust/cargo/bin
 - cp target/debug/cargo-clippy ~/rust/cargo/bin/cargo-clippy
 - PATH=$PATH:~/rust/cargo/bin cargo clippy -- -D clippy
 - cd clippy_lints && PATH=$PATH:~/rust/cargo/bin cargo clippy -- -D clippy && cd ..

after_success:
- ./.github/deploy.sh
- ./.github/clippy-service.sh
